-- LEAD MINER PRO - security and integrity hardening
ALTER TABLE public.mineracoes ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE public.leads ALTER COLUMN user_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mineracoes_user_id ON public.mineracoes(user_id);
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON public.leads(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_instances_user_id ON public.saved_instances(user_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_groups_user_id ON public.dispatch_groups(user_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_group_contacts_user_id ON public.dispatch_group_contacts(user_id);
CREATE INDEX IF NOT EXISTS idx_message_templates_user_id ON public.message_templates(user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_dispatches_user_id ON public.scheduled_dispatches(user_id);
DROP POLICY IF EXISTS "Users can update own mineracoes" ON public.mineracoes;
CREATE POLICY "Users can update own mineracoes" ON public.mineracoes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own leads" ON public.leads;
CREATE POLICY "Users can update own leads" ON public.leads FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own settings" ON public.user_settings;
CREATE POLICY "Users can update own settings" ON public.user_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own instances" ON public.saved_instances;
CREATE POLICY "Users can update own instances" ON public.saved_instances FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own dispatch groups" ON public.dispatch_groups;
CREATE POLICY "Users can update own dispatch groups" ON public.dispatch_groups FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own group contacts" ON public.dispatch_group_contacts;
CREATE POLICY "Users can update own group contacts" ON public.dispatch_group_contacts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own templates" ON public.message_templates;
CREATE POLICY "Users can update own templates" ON public.message_templates FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own schedules" ON public.scheduled_dispatches;
CREATE POLICY "Users can update own schedules" ON public.scheduled_dispatches FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own cnpj_leads" ON public.cnpj_leads;
CREATE POLICY "Users can update own cnpj_leads" ON public.cnpj_leads FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_role() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_profile() FROM PUBLIC, anon, authenticated;
