// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejpvovdixjcsrjgasrym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcHZvdmRpeGpjc3JqZ2FzcnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4Mzk0NzksImV4cCI6MjEwNTQxNTQ3OX0.v8a0-ash9s_Sns-s-ZQVBgxwBNWNEzcaR8XLCljE9Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
